


ALTER USER system QUOTA UNLIMITED ON USERS;

ALTER USER hr ACCOUNT UNLOCK;

ALTER USER hr IDENTIFIED BY oracle;

ALTER USER HR QUOTA UNLIMITED ON USERS;

CREATE USER HR IDENTIFIED BY hr123;
GRANT CONNECT, RESOURCE TO HR;

CREATE TABLE HR.REGIONS (
    REGION_ID NUMBER CONSTRAINT REGION_ID_NN NOT NULL ENABLE,
    REGION_NAME VARCHAR2(25),
    CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID)
);


